import type { SnowResort } from "@/lib/snowResorts";

export const POWDER_SNOW_RESORTS: readonly SnowResort[] = [
  {
    slug: "palisades-tahoe",
    name: "Palisades Tahoe",
    country: "USA",
    continent: "North America",
    region: "California, Sierra Nevada (Lake Tahoe)",
    kind: "Alpine resort",
    description:
      "Olympic Valley resort that hosted the 1960 Winter Olympics; McConkey's drops off the KT-22 ridge into cliff-studded expert terrain above the base area.",
    featuredRun: "McConkey's",
    powderEntry: true,
    lat: 39.191,
    lon: -120.245,
    baseElevation: 1890,
    summitElevation: 2758,
    topElevation: 2758,
    zoom: 13.2,
    bearing: 20,
    assetBase: "/ski-resorts/palisades-tahoe",
  },
  {
    slug: "heavenly",
    name: "Heavenly",
    country: "USA",
    continent: "North America",
    region: "California/Nevada, Lake Tahoe",
    kind: "Alpine resort",
    description:
      "Cross-state resort above South Lake Tahoe whose Gunbarrel mogul face plunges straight down to the California base lodge.",
    featuredRun: "Gunbarrel",
    powderEntry: true,
    lat: 38.9355,
    lon: -119.9395,
    baseElevation: 1907,
    summitElevation: 3068,
    topElevation: 3068,
    zoom: 13.0,
    bearing: -15,
    assetBase: "/ski-resorts/heavenly",
  },
  {
    slug: "snowbasin",
    name: "Snowbasin",
    country: "USA",
    continent: "North America",
    region: "Utah, Wasatch Range",
    kind: "Alpine resort",
    description:
      "Huntsville-area resort that hosted the 2002 Olympic downhills; Grizzly is the men's downhill course dropping from Allen Peak.",
    featuredRun: "Grizzly",
    powderEntry: true,
    lat: 41.208,
    lon: -111.865,
    baseElevation: 1948,
    summitElevation: 2850,
    topElevation: 2885,
    zoom: 13.0,
    bearing: 25,
    assetBase: "/ski-resorts/snowbasin",
  },
  {
    slug: "jackson-hole",
    name: "Jackson Hole",
    country: "USA",
    continent: "North America",
    region: "Wyoming, Teton Range",
    kind: "Alpine resort",
    description:
      "Teton Village resort with 1262 m of continuous vertical; Corbet's Couloir is the cornice-guarded chute just below the Rendezvous Mountain tram summit.",
    featuredRun: "Corbet's Couloir",
    powderEntry: true,
    lat: 43.587,
    lon: -110.873,
    baseElevation: 1924,
    summitElevation: 3185,
    topElevation: 3185,
    zoom: 13.0,
    bearing: 30,
    assetBase: "/ski-resorts/jackson-hole",
  },
  {
    slug: "aspen-mountain",
    name: "Aspen Mountain",
    country: "USA",
    continent: "North America",
    region: "Colorado, Elk Mountains",
    kind: "Alpine resort",
    description:
      "Steep town-side mountain above Aspen; Walsh's is a double-black glade on the eastern flank near the Gentleman's Ridge area.",
    featuredRun: "Walsh's",
    powderEntry: true,
    lat: 39.178,
    lon: -106.812,
    baseElevation: 2422,
    summitElevation: 3417,
    topElevation: 3417,
    zoom: 13.2,
    bearing: -20,
    assetBase: "/ski-resorts/aspen-mountain",
  },
  {
    slug: "stowe",
    name: "Stowe",
    country: "USA",
    continent: "North America",
    region: "Vermont, Green Mountains",
    kind: "Alpine resort",
    description:
      "Vermont's classic resort on Mount Mansfield; Goat is one of the narrow, icy Front Four trails under the FourRunner Quad.",
    featuredRun: "Goat",
    powderEntry: true,
    lat: 44.528,
    lon: -72.786,
    baseElevation: 475,
    summitElevation: 1134,
    topElevation: 1339,
    zoom: 13.4,
    bearing: -30,
    assetBase: "/ski-resorts/stowe",
  },
  {
    slug: "mount-saint-elias",
    name: "Mount Saint Elias",
    country: "USA/Canada",
    continent: "North America",
    region: "Alaska / Yukon, Saint Elias Mountains",
    kind: "Expedition descent",
    description:
      "Second-highest peak in both the USA and Canada, offering an unrivalled summit-to-tidewater ski descent toward Icy Bay.",
    featuredRun: "Mount St Elias",
    powderEntry: true,
    lat: 60.2922,
    lon: -140.9314,
    baseElevation: 100,
    summitElevation: 5489,
    topElevation: 5489,
    zoom: 10.5,
    bearing: 40,
    assetBase: "/ski-resorts/mount-saint-elias",
  },
  {
    slug: "whistler-blackcomb",
    name: "Whistler Blackcomb",
    country: "Canada",
    continent: "North America",
    region: "British Columbia, Coast Mountains",
    kind: "Alpine resort",
    description:
      "North America's largest resort; Couloir Extreme is a sustained steep chute on Blackcomb below the Glacier Express and Showcase zone.",
    featuredRun: "Couloir Extreme",
    powderEntry: true,
    lat: 50.089,
    lon: -122.888,
    baseElevation: 675,
    summitElevation: 2240,
    topElevation: 2440,
    zoom: 12.6,
    bearing: 35,
    assetBase: "/ski-resorts/whistler-blackcomb",
  },
  {
    slug: "revelstoke-mountain-resort",
    name: "Revelstoke",
    country: "Canada",
    continent: "North America",
    region: "British Columbia, Selkirk Mountains",
    kind: "Alpine resort",
    description:
      "Mount Mackenzie resort with North America's greatest lift-served vertical; North Bowl is the vast alpine bowl accessed from the Stoke chair.",
    featuredRun: "North Bowl",
    powderEntry: true,
    lat: 50.95,
    lon: -118.14,
    baseElevation: 512,
    summitElevation: 2225,
    topElevation: 2456,
    zoom: 12.6,
    bearing: -35,
    assetBase: "/ski-resorts/revelstoke-mountain-resort",
  },
  {
    slug: "lake-louise",
    name: "Lake Louise",
    country: "Canada",
    continent: "North America",
    region: "Alberta, Banff National Park (Canadian Rockies)",
    kind: "Alpine resort",
    description:
      "Banff National Park resort on Whitehorn Mountain; the Whitehorn III gullies are steep hike-and-drop chutes off the Summit Platter into the back bowls.",
    featuredRun: "I Gully, Whitehorn III",
    powderEntry: true,
    lat: 51.455,
    lon: -116.165,
    baseElevation: 1646,
    summitElevation: 2637,
    topElevation: 2670,
    zoom: 12.8,
    bearing: 30,
    assetBase: "/ski-resorts/lake-louise",
  },
  {
    slug: "mont-sainte-anne",
    name: "Mont-Sainte-Anne",
    country: "Canada",
    continent: "North America",
    region: "Quebec (Laurentians, Côte-de-Beaupré)",
    kind: "Alpine resort",
    description:
      "Laurentian resort above the St. Lawrence near Quebec City, with 625 m of vertical and groomed expert pistes such as La Crête on its south face.",
    featuredRun: "La Crête",
    powderEntry: true,
    lat: 47.077,
    lon: -70.905,
    baseElevation: 175,
    summitElevation: 800,
    topElevation: 800,
    zoom: 13.2,
    bearing: 15,
    assetBase: "/ski-resorts/mont-sainte-anne",
  },
  {
    slug: "kangaamiut-heliski",
    name: "Kangaamiut",
    country: "Greenland",
    continent: "North America",
    region: "Qeqqata, West Greenland",
    kind: "Expedition descent",
    description:
      "Heli-accessed glacier and couloir descents on the fjord mountains behind Kangaamiut island, running from summits near 2000 m straight to sea level.",
    featuredRun: "Revelation",
    powderEntry: true,
    lat: 65.85,
    lon: -52.9,
    baseElevation: 0,
    summitElevation: 2000,
    topElevation: 2000,
    zoom: 10.5,
    bearing: 30,
    assetBase: "/ski-resorts/kangaamiut-heliski",
  },
  {
    slug: "lyngen-alps",
    name: "Lyngen Alps",
    country: "Norway",
    continent: "Europe",
    region: "Troms (Lyngen and Karlsøy municipalities)",
    kind: "Backcountry zone",
    description:
      "Arctic ski-touring range where glaciated peaks up to 1834 m rise directly from the fjords, skied largely by boat- and road-accessed spring touring.",
    featuredRun: "Lyngen Peninsula",
    powderEntry: true,
    lat: 69.55,
    lon: 20.05,
    baseElevation: 0,
    summitElevation: 1834,
    topElevation: 1834,
    zoom: 10.5,
    bearing: -30,
    assetBase: "/ski-resorts/lyngen-alps",
  },
  {
    slug: "are",
    name: "Åre",
    country: "Sweden",
    continent: "Europe",
    region: "Jämtland",
    kind: "Alpine resort",
    description:
      "Sweden's largest ski resort on Åreskutan, whose lift-served slopes drop over 870 m through World Cup pistes to the village and lake.",
    featuredRun: "Lundsrappet",
    powderEntry: true,
    lat: 63.408,
    lon: 13.075,
    baseElevation: 380,
    summitElevation: 1260,
    topElevation: 1420,
    zoom: 12.5,
    bearing: 20,
    assetBase: "/ski-resorts/are",
  },
  {
    slug: "nevis-range",
    name: "Nevis Range",
    country: "United Kingdom (Scotland)",
    continent: "Europe",
    region: "Highland (Lochaber)",
    kind: "Ski area",
    description:
      "Scotland's highest ski area on Aonach Mòr, whose east-facing Back Corries including Coire Dubh offer steep, cornice-guarded off-piste terrain.",
    featuredRun: "Coire Dubh",
    powderEntry: true,
    lat: 56.82,
    lon: -4.958,
    baseElevation: 91,
    summitElevation: 1190,
    topElevation: 1221,
    zoom: 12.8,
    bearing: -40,
    assetBase: "/ski-resorts/nevis-range",
  },
  {
    slug: "baqueira-beret",
    name: "Baqueira Beret",
    country: "Spain",
    continent: "Europe",
    region: "Catalonia (Val d'Aran / Pallars Sobirà, Pyrenees)",
    kind: "Alpine resort",
    description:
      "Spain's largest ski resort in the Aran Valley Pyrenees, spanning 1500-2610 m across the Baqueira, Beret, Bonaigua and Baciver sectors.",
    featuredRun: "Luis Arias",
    powderEntry: true,
    lat: 42.7,
    lon: 0.95,
    baseElevation: 1500,
    summitElevation: 2610,
    topElevation: 2610,
    zoom: 12.5,
    bearing: 25,
    assetBase: "/ski-resorts/baqueira-beret",
  },
  {
    slug: "grand-tourmalet-pic-du-midi",
    name: "Pic du Midi",
    country: "France",
    continent: "Europe",
    region: "Hautes-Pyrénées, Occitanie",
    kind: "Alpine resort",
    description:
      "Largest French Pyrenean ski area straddling the Col du Tourmalet, with a cable car to the 2877 m Pic du Midi observatory serving unpatrolled freeride descents.",
    featuredRun: "Pic du Midi",
    powderEntry: true,
    lat: 42.925,
    lon: 0.165,
    baseElevation: 1250,
    summitElevation: 2877,
    topElevation: 2877,
    zoom: 12.2,
    bearing: -25,
    assetBase: "/ski-resorts/grand-tourmalet-pic-du-midi",
  },
  {
    slug: "la-plagne",
    name: "La Plagne",
    country: "France",
    continent: "Europe",
    region: "Savoie, Tarentaise",
    kind: "Alpine resort",
    description:
      "Vast Tarentaise resort of eleven villages whose high sector climbs onto the Bellecôte glaciers, with steep off-piste faces below the 3417 m Sommet de Bellecôte.",
    featuredRun: "Bellecôte",
    powderEntry: true,
    lat: 45.49,
    lon: 6.76,
    baseElevation: 1250,
    summitElevation: 3080,
    topElevation: 3417,
    zoom: 12.3,
    bearing: 30,
    assetBase: "/ski-resorts/la-plagne",
  },
  {
    slug: "alpe-dhuez",
    name: "Alpe d'Huez",
    country: "France",
    continent: "Europe",
    region: "Isère, Oisans (Grandes Rousses)",
    kind: "Alpine resort",
    description:
      "Sun-facing Oisans resort topped by the 3330 m Pic Blanc cable car, from which the 16 km Sarenne black run descends 1820 m into the Sarenne gorge.",
    featuredRun: "Sarenne",
    powderEntry: true,
    lat: 45.09,
    lon: 6.12,
    baseElevation: 1125,
    summitElevation: 3330,
    topElevation: 3330,
    zoom: 12,
    bearing: -35,
    assetBase: "/ski-resorts/alpe-dhuez",
  },
  {
    slug: "val-disere",
    name: "Val d'Isère",
    country: "France",
    continent: "Europe",
    region: "Savoie, Tarentaise",
    kind: "Alpine resort",
    description:
      "High Tarentaise resort linked with Tignes, home to the Olympic Face de Bellevarde downhill dropping about 960 m from the Rocher de Bellevarde to the village.",
    featuredRun: "Face de Bellevarde",
    powderEntry: true,
    lat: 45.447,
    lon: 6.975,
    baseElevation: 1550,
    summitElevation: 3456,
    topElevation: 3456,
    zoom: 13,
    bearing: 35,
    assetBase: "/ski-resorts/val-disere",
  },
  {
    slug: "les-arcs",
    name: "Les Arcs",
    country: "France",
    continent: "Europe",
    region: "Savoie, Tarentaise Valley, Vanoise Massif",
    kind: "Alpine resort",
    description:
      "Les Arcs' cable-car-served Aiguille Rouge summit at 3,226 m launches a 7 km run dropping over 2,000 m to the village of Villaroger.",
    featuredRun: "Aiguille Rouge",
    powderEntry: true,
    lat: 45.572,
    lon: 6.855,
    baseElevation: 1200,
    summitElevation: 3226,
    topElevation: 3227,
    zoom: 12.2,
    bearing: 30,
    assetBase: "/ski-resorts/les-arcs",
  },
  {
    slug: "chamonix-vallee-blanche",
    name: "Chamonix-Mont-Blanc",
    country: "France",
    continent: "Europe",
    region: "Haute-Savoie, Mont Blanc Massif",
    kind: "Backcountry zone",
    description:
      "An unmarked 20 km glacier itinerary from the Aiguille du Midi cable car across the Géant, Tacul and Mer de Glace glaciers toward Montenvers or Chamonix.",
    featuredRun: "Vallée Blanche",
    powderEntry: true,
    lat: 45.9,
    lon: 6.92,
    baseElevation: 1913,
    summitElevation: 3842,
    topElevation: 3842,
    zoom: 11.8,
    bearing: 25,
    assetBase: "/ski-resorts/chamonix-vallee-blanche",
  },
  {
    slug: "garmisch-classic",
    name: "Garmisch Classic",
    country: "Germany",
    continent: "Europe",
    region: "Bavaria, Wetterstein Mountains",
    kind: "Alpine resort",
    description:
      "The Kandahar World Cup downhill on Kreuzeck drops about 920 m through the Garmisch Classic area beneath the Alpspitze, finishing near Garmisch-Partenkirchen.",
    featuredRun: "Kandahar",
    powderEntry: true,
    lat: 47.468,
    lon: 11.064,
    baseElevation: 700,
    summitElevation: 2050,
    topElevation: 2050,
    zoom: 13.0,
    bearing: -20,
    assetBase: "/ski-resorts/garmisch-classic",
  },
  {
    slug: "mittenwald-karwendel",
    name: "Dammkar",
    country: "Germany",
    continent: "Europe",
    region: "Bavaria, Karwendel Alps",
    kind: "Backcountry zone",
    description:
      "The Dammkar is an ungroomed 7 km ski route from the Karwendelbahn top station at 2,244 m down a high cirque to Mittenwald, Germany's longest.",
    featuredRun: "Dammkar",
    powderEntry: true,
    lat: 47.435,
    lon: 11.29,
    baseElevation: 933,
    summitElevation: 2244,
    topElevation: 2385,
    zoom: 12.8,
    bearing: 30,
    assetBase: "/ski-resorts/mittenwald-karwendel",
  },
  {
    slug: "st-anton-ski-arlberg",
    name: "St. Anton am Arlberg",
    country: "Austria",
    continent: "Europe",
    region: "Tyrol / Vorarlberg, Lechtal Alps",
    kind: "Alpine resort",
    description:
      "The 2,811 m Valluga, reached by a two-stage cable car from Galzig, is Ski Arlberg's highest point and gateway to steep off-piste descents toward Zürs.",
    featuredRun: "Valluga",
    powderEntry: true,
    lat: 47.15,
    lon: 10.23,
    baseElevation: 1304,
    summitElevation: 2811,
    topElevation: 2811,
    zoom: 12.2,
    bearing: -30,
    assetBase: "/ski-resorts/st-anton-ski-arlberg",
  },
  {
    slug: "kitzbuehel",
    name: "Kitzbühel",
    country: "Austria",
    continent: "Europe",
    region: "Tyrol, Kitzbühel Alps",
    kind: "Alpine resort",
    description:
      "The Streif downhill on the Hahnenkamm falls 860 m over 3.3 km from a 1,665 m start to the finish above Kitzbühel town.",
    featuredRun: "Streif",
    powderEntry: true,
    lat: 47.428,
    lon: 12.375,
    baseElevation: 800,
    summitElevation: 2000,
    topElevation: 2000,
    zoom: 13.2,
    bearing: 20,
    assetBase: "/ski-resorts/kitzbuehel",
  },
  {
    slug: "patscherkofel",
    name: "Patscherkofel",
    country: "Austria",
    continent: "Europe",
    region: "Tyrol, Tux Alps",
    kind: "Ski area",
    description:
      "Innsbruck's home mountain hosted the 1964 and 1976 Olympic downhills; its 7.5 km Olympiaabfahrt runs from about 1,960 m down to Igls.",
    featuredRun: "Olympia Run",
    powderEntry: true,
    lat: 47.215,
    lon: 11.435,
    baseElevation: 900,
    summitElevation: 1960,
    topElevation: 2246,
    zoom: 13.0,
    bearing: 40,
    assetBase: "/ski-resorts/patscherkofel",
  },
  {
    slug: "dachstein-ramsau",
    name: "Dachstein Glacier",
    country: "Austria",
    continent: "Europe",
    region: "Styria / Upper Austria, Dachstein Massif",
    kind: "Backcountry zone",
    description:
      "The Edelgrieß freeride descent leaves the 2,700 m Hunerkogel station via a ladder and tunnel, dropping roughly 1,000 m down the Dachstein's south flank.",
    featuredRun: "Edelgrieß",
    powderEntry: true,
    lat: 47.458,
    lon: 13.628,
    baseElevation: 1702,
    summitElevation: 2700,
    topElevation: 2995,
    zoom: 13.0,
    bearing: 20,
    assetBase: "/ski-resorts/dachstein-ramsau",
  },
  {
    slug: "stubai-glacier",
    name: "Stubai Glacier",
    country: "Austria",
    continent: "Europe",
    region: "Tyrol, Stubai Alps",
    kind: "Alpine resort",
    description:
      "Ski route 35 Wilde Grub'n leaves the Wildspitz lift at about 3,210 m and descends roughly 10 km and 1,500 m to the Eisgrat valley station.",
    featuredRun: "Wilde Grub'n",
    powderEntry: true,
    lat: 46.99,
    lon: 11.12,
    baseElevation: 1750,
    summitElevation: 3210,
    topElevation: 3210,
    zoom: 12.3,
    bearing: -20,
    assetBase: "/ski-resorts/stubai-glacier",
  },
  {
    slug: "muerren-schilthorn",
    name: "Mürren-Schilthorn",
    country: "Switzerland",
    continent: "Europe",
    region: "Bern, Bernese Oberland",
    kind: "Alpine resort",
    description:
      "The Inferno amateur race, held since 1928, runs 14.9 km from below the 2,970 m Schilthorn through Mürren to Lauterbrunnen.",
    featuredRun: "Inferno",
    powderEntry: true,
    lat: 46.565,
    lon: 7.86,
    baseElevation: 796,
    summitElevation: 2970,
    topElevation: 2970,
    zoom: 12.2,
    bearing: 30,
    assetBase: "/ski-resorts/muerren-schilthorn",
  },
  {
    slug: "verbier-mont-fort",
    name: "Verbier",
    country: "Switzerland",
    continent: "Europe",
    region: "Valais / Pennine Alps",
    kind: "Alpine resort",
    description:
      "The Backside is Verbier's classic lift-accessed off-piste descent off the north-east face of Mont Fort, the 3,330 m summit of the 4 Vallées.",
    featuredRun: "Backside",
    powderEntry: true,
    lat: 46.078,
    lon: 7.33,
    baseElevation: 821,
    summitElevation: 3330,
    topElevation: 3330,
    zoom: 12.6,
    bearing: 30,
    assetBase: "/ski-resorts/verbier-mont-fort",
  },
  {
    slug: "diavolezza-lagalb",
    name: "Diavolezza–Lagalb",
    country: "Switzerland",
    continent: "Europe",
    region: "Graubünden / Engadin–Bernina Range",
    kind: "Ski area",
    description:
      "Switzerland's longest marked glacier run descends about eight kilometres over the Pers and Morteratsch glaciers beneath Piz Palü and Piz Bernina.",
    featuredRun: "Diavolezza Glacier",
    powderEntry: true,
    lat: 46.405,
    lon: 9.945,
    baseElevation: 1896,
    summitElevation: 2978,
    topElevation: 2978,
    zoom: 12.4,
    bearing: -45,
    assetBase: "/ski-resorts/diavolezza-lagalb",
  },
  {
    slug: "champery-portes-du-soleil",
    name: "Champéry–Les Crosets",
    country: "Switzerland/France",
    continent: "Europe",
    region: "Valais / Chablais Alps",
    kind: "Alpine resort",
    description:
      "The Pas de Chavanette, dubbed the Swiss Wall, drops 331 moguled metres over one steep kilometre on the Franco-Swiss border above Les Crosets.",
    featuredRun: "The Wall/Paradise",
    powderEntry: true,
    lat: 46.1735,
    lon: 6.8055,
    baseElevation: 1050,
    summitElevation: 2277,
    topElevation: 2277,
    zoom: 12.9,
    bearing: -30,
    assetBase: "/ski-resorts/champery-portes-du-soleil",
  },
  {
    slug: "davos-klosters-parsenn",
    name: "Davos Klosters",
    country: "Switzerland",
    continent: "Europe",
    region: "Graubünden / Prättigau–Davos",
    kind: "Alpine resort",
    description:
      "Discovered in 1895, the classic Parsenn run covers about twelve kilometres and 2,000 vertical metres from the Weissfluhgipfel down to Küblis.",
    featuredRun: "Parsenn to Küblis",
    powderEntry: true,
    lat: 46.872,
    lon: 9.785,
    baseElevation: 810,
    summitElevation: 2844,
    topElevation: 2844,
    zoom: 11.5,
    bearing: 10,
    assetBase: "/ski-resorts/davos-klosters-parsenn",
  },
  {
    slug: "zermatt-cervinia-klein-matterhorn",
    name: "Zermatt",
    country: "Switzerland/Italy",
    continent: "Europe",
    region: "Valais–Aosta / Pennine Alps",
    kind: "Alpine resort",
    description:
      "Europe's highest lift-served terrain tops out at 3,883 m on the Klein Matterhorn, linking the year-round glacier skiing of Zermatt and Breuil-Cervinia.",
    featuredRun: "Klein Matterhorn",
    powderEntry: true,
    lat: 45.9383,
    lon: 7.7297,
    baseElevation: 1620,
    summitElevation: 3883,
    topElevation: 3883,
    zoom: 12.2,
    bearing: -30,
    assetBase: "/ski-resorts/zermatt-cervinia-klein-matterhorn",
  },
  {
    slug: "cortina-dampezzo-tofane",
    name: "Cortina d'Ampezzo",
    country: "Italy",
    continent: "Europe",
    region: "Veneto / Dolomites",
    kind: "Alpine resort",
    description:
      "The Olympia delle Tofane is Cortina's regular women's World Cup downhill, raced in the 1956 and Milano Cortina 2026 Winter Olympics.",
    featuredRun: "Olympia",
    powderEntry: true,
    lat: 46.535,
    lon: 12.12,
    baseElevation: 1217,
    summitElevation: 2828,
    topElevation: 3244,
    zoom: 12.9,
    bearing: 20,
    assetBase: "/ski-resorts/cortina-dampezzo-tofane",
  },
  {
    slug: "alagna-monterosa-ski",
    name: "Alagna Valsesia",
    country: "Italy",
    continent: "Europe",
    region: "Piedmont–Aosta / Monte Rosa",
    kind: "Backcountry zone",
    description:
      "The Balma is a celebrated freeride valley dropping from Punta Indren and Passo dei Salati past abandoned lift ruins toward Alagna and the Sesia river.",
    featuredRun: "Balma",
    powderEntry: true,
    lat: 45.875,
    lon: 7.9,
    baseElevation: 1212,
    summitElevation: 3275,
    topElevation: 3275,
    zoom: 12.4,
    bearing: -35,
    assetBase: "/ski-resorts/alagna-monterosa-ski",
  },
  {
    slug: "val-mesdi-sella-group",
    name: "Val Mesdì",
    country: "Italy",
    continent: "Europe",
    region: "Trentino–South Tyrol / Dolomites",
    kind: "Backcountry zone",
    description:
      "The Dolomites' best-known off-piste couloir threads the Sella massif from the Sass Pordoi cable car down a narrow ravine to Colfosco.",
    featuredRun: "Val Mesdì",
    powderEntry: true,
    lat: 46.525,
    lon: 11.835,
    baseElevation: 1565,
    summitElevation: 2950,
    topElevation: 3152,
    zoom: 13.0,
    bearing: 15,
    assetBase: "/ski-resorts/val-mesdi-sella-group",
  },
  {
    slug: "mount-etna",
    name: "Mount Etna",
    country: "Italy",
    continent: "Europe",
    region: "Sicily",
    kind: "Volcanic ski area",
    description:
      "Europe's most active volcano offers lift skiing at Piano Provenzana and Nicolosi plus guided ski descents from near the summit craters.",
    featuredRun: "Mount Etna",
    powderEntry: true,
    lat: 37.765,
    lon: 15.01,
    baseElevation: 1806,
    summitElevation: 2500,
    topElevation: 3357,
    zoom: 11.6,
    bearing: -30,
    assetBase: "/ski-resorts/mount-etna",
  },
  {
    slug: "kanin-sella-nevea",
    name: "Kanin–Sella Nevea",
    country: "Slovenia/Italy",
    continent: "Europe",
    region: "Julian Alps (Goriška / Friuli-Venezia Giulia)",
    kind: "Ski area",
    description:
      "Slovenia's highest ski area links Bovec's Kanin cable car with Sella Nevea in Italy across the Julian Alps border ridge.",
    featuredRun: "Kanin to Sella Nevea",
    powderEntry: true,
    lat: 46.355,
    lon: 13.52,
    baseElevation: 1140,
    summitElevation: 2292,
    topElevation: 2292,
    zoom: 12.6,
    bearing: 25,
    assetBase: "/ski-resorts/kanin-sella-nevea",
  },
  {
    slug: "kasprowy-wierch-zakopane",
    name: "Kasprowy Wierch",
    country: "Poland",
    continent: "Europe",
    region: "Tatra Mountains, Lesser Poland Voivodeship",
    kind: "Ski area",
    description:
      "Steep lift-served piste on the north-west flank of Kasprowy Wierch inside Tatra National Park, reached by cable car from Zakopane.",
    featuredRun: "Goryczkowa",
    powderEntry: true,
    lat: 49.2345,
    lon: 19.9775,
    baseElevation: 1355,
    summitElevation: 1958,
    topElevation: 1987,
    zoom: 13.4,
    bearing: 20,
    assetBase: "/ski-resorts/kasprowy-wierch-zakopane",
  },
  {
    slug: "palandoken-erzurum",
    name: "Palandöken",
    country: "Turkey",
    continent: "Asia",
    region: "Erzurum Province, Eastern Anatolia",
    kind: "Alpine resort",
    description:
      "High, dry, treeless resort on Ejder peak above Erzurum, with long sustained pistes and easily reached off-piste faces served by gondola and chairlifts.",
    featuredRun: "Itinerary 19",
    powderEntry: true,
    lat: 39.852,
    lon: 41.282,
    baseElevation: 2200,
    summitElevation: 3176,
    topElevation: 3176,
    zoom: 12.8,
    bearing: -40,
    assetBase: "/ski-resorts/palandoken-erzurum",
  },
  {
    slug: "rosa-khutor-sochi",
    name: "Rosa Khutor",
    country: "Russia",
    continent: "Europe",
    region: "Krasnaya Polyana, Krasnodar Krai, Western Caucasus",
    kind: "Alpine resort",
    description:
      "Purpose-built Caucasus resort whose Bernhard Russi-designed race piste drops off the Aibga ridge and hosted the 2014 Olympic alpine events.",
    featuredRun: "Olympic Downhill",
    powderEntry: true,
    lat: 43.652,
    lon: 40.307,
    baseElevation: 940,
    summitElevation: 2320,
    topElevation: 2320,
    zoom: 12.4,
    bearing: 15,
    assetBase: "/ski-resorts/rosa-khutor-sochi",
  },
  {
    slug: "gulmarg-apharwat",
    name: "Gulmarg",
    country: "India",
    continent: "Asia",
    region: "Baramulla district, Jammu and Kashmir, Pir Panjal range",
    kind: "Backcountry zone",
    description:
      "Gondola-accessed Himalayan bowls off Apharwat's southern shoulder that drain into forested gullies ending at the roadside village of Drang.",
    featuredRun: "Southeast Shoulder to Drang",
    powderEntry: true,
    lat: 34.025,
    lon: 74.38,
    baseElevation: 2160,
    summitElevation: 3980,
    topElevation: 4200,
    zoom: 11.8,
    bearing: -25,
    assetBase: "/ski-resorts/gulmarg-apharwat",
  },
  {
    slug: "annapurna-machapuchare-base-camp",
    name: "Annapurna Sanctuary",
    country: "Nepal",
    continent: "Asia",
    region: "Kaski district, Gandaki Province, Annapurna Himal",
    kind: "Expedition descent",
    description:
      "Trek-in glacial slopes inside the Annapurna Sanctuary beneath unclimbed Machapuchare, skied on foot-powered expeditions with no lifts or patrol.",
    featuredRun: "Fishtail Base Camp Run",
    powderEntry: true,
    lat: 28.515,
    lon: 83.925,
    baseElevation: 3700,
    summitElevation: 4300,
    topElevation: 6993,
    zoom: 11.5,
    bearing: 30,
    assetBase: "/ski-resorts/annapurna-machapuchare-base-camp",
  },
  {
    slug: "niseko-united",
    name: "Niseko United",
    country: "Japan",
    continent: "Asia",
    region: "Hokkaido, Shiribeshi, Mount Niseko-Annupuri",
    kind: "Alpine resort",
    description:
      "Avalanche-controlled gully zone beneath the Niseko Village gondola, entered through Gate 11 and prized for deep, sheltered fall-line powder.",
    featuredRun: "Mizuno no Sawa",
    powderEntry: true,
    lat: 42.857,
    lon: 140.67,
    baseElevation: 280,
    summitElevation: 1170,
    topElevation: 1308,
    zoom: 13.0,
    bearing: -20,
    assetBase: "/ski-resorts/niseko-united",
  },
  {
    slug: "portillo",
    name: "Portillo",
    country: "Chile",
    continent: "South America",
    region: "Los Andes Province, Valparaíso Region, Central Andes",
    kind: "Alpine resort",
    description:
      "Steep avalanche-prone face above Laguna del Inca served by Portillo's slingshot va-et-vient surface lift, which launches five skiers at once.",
    featuredRun: "Roca Jack",
    powderEntry: true,
    lat: -32.837,
    lon: -70.133,
    baseElevation: 2880,
    summitElevation: 3310,
    topElevation: 3330,
    zoom: 13.4,
    bearing: 40,
    assetBase: "/ski-resorts/portillo",
  },
  {
    slug: "las-lenas",
    name: "Las Leñas",
    country: "Argentina",
    continent: "South America",
    region: "Malargüe, Mendoza Province, Andes",
    kind: "Alpine resort",
    description:
      "Long technical couloir dropping from the Marte chairlift ridge, the best-known of dozens of lift-accessed extreme lines above the Las Leñas base.",
    featuredRun: "Eduardo's",
    powderEntry: true,
    lat: -35.148,
    lon: -70.093,
    baseElevation: 2240,
    summitElevation: 3430,
    topElevation: 3430,
    zoom: 12.8,
    bearing: 30,
    assetBase: "/ski-resorts/las-lenas",
  },
  {
    slug: "treble-cone",
    name: "Treble Cone",
    country: "New Zealand",
    continent: "Oceania",
    region: "Otago, Southern Alps near Wanaka",
    kind: "Ski area",
    description:
      "In-bounds chutes and couloirs in Treble Cone's Motatapu Basin, reached beyond Saddle Basin and among New Zealand's most demanding patrolled terrain.",
    featuredRun: "Motatapu Chutes",
    powderEntry: true,
    lat: -44.64,
    lon: 168.88,
    baseElevation: 1260,
    summitElevation: 1960,
    topElevation: 2088,
    zoom: 13.0,
    bearing: 20,
    assetBase: "/ski-resorts/treble-cone",
  },
] as const;
